workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_ID: "com.kletterwelt.beta"
        PACKAGE_NAME: "com.kletterwelt.beta"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run cap:sync
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          cd ../..
      - name: Set up automatic code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist ios/App/exportOptions.plist
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jalthoff@moonsight.media
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        
        # Automatisches Upload zu TestFlight
        submit_to_testflight: true
        beta_groups:
          - Internal Testing

