workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - app_store_credentials # Gruppe für App Store Connect Credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_ID: "com.kletterwelt.beta"
        PACKAGE_NAME: "com.kletterwelt.beta"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run cap:sync
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcodebuild build-for-testing \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Archive iOS app
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/App.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          xcode-project export-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jalthoff@moonsight.media
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        
        # Automatisches Upload zu TestFlight
        submit_to_testflight: true
        beta_groups:
          - Internal Testing

