-- Fix Hostinger rendition validation in the async video callback.
--
-- The original function used ordinary standard-conforming SQL strings with
-- double backslashes. PostgreSQL therefore passed two backslashes to the
-- regular-expression engine and rejected valid URLs containing normal dots.
-- Escape strings below make the intended regex escaping explicit.

CREATE OR REPLACE FUNCTION public.sync_boulder_video_job(
  p_boulder_id uuid,
  p_upload_session_id text,
  p_job_id uuid,
  p_status text,
  p_hd_url text DEFAULT NULL,
  p_sd_url text DEFAULT NULL,
  p_low_url text DEFAULT NULL,
  p_error text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_boulder public.boulders%ROWTYPE;
  v_family text;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'Only service_role may synchronize video jobs' USING ERRCODE = '42501';
  END IF;

  IF p_upload_session_id IS NULL
     OR p_upload_session_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
     OR p_job_id IS NULL
     OR p_status IS NULL
     OR p_status NOT IN ('queued', 'processing', 'completed', 'failed') THEN
    RAISE EXCEPTION 'Invalid video job payload' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_boulder
  FROM public.boulders
  WHERE id = p_boulder_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  -- A different client session or a replaced job must never be overwritten by
  -- a delayed Hostinger callback. A terminal result cannot be downgraded.
  IF v_boulder.beta_video_upload_session_id IS DISTINCT FROM lower(p_upload_session_id)
     OR (v_boulder.beta_video_job_id IS NOT NULL AND v_boulder.beta_video_job_id IS DISTINCT FROM p_job_id)
     OR (p_status IN ('queued', 'processing') AND v_boulder.beta_video_status IN ('ready', 'failed')) THEN
    RETURN false;
  END IF;

  IF p_status IN ('queued', 'processing') THEN
    UPDATE public.boulders
    SET beta_video_status = p_status,
        beta_video_job_id = p_job_id,
        beta_video_error = NULL,
        beta_video_updated_at = now()
    WHERE id = p_boulder_id;
    RETURN true;
  END IF;

  IF p_status = 'failed' THEN
    IF v_boulder.beta_video_status = 'ready' THEN
      RETURN false;
    END IF;

    UPDATE public.boulders
    SET beta_video_status = 'failed',
        beta_video_job_id = p_job_id,
        beta_video_error = NULLIF(left(COALESCE(p_error, 'Video processing failed'), 1000), ''),
        beta_video_updated_at = now()
    WHERE id = p_boulder_id;
    RETURN true;
  END IF;

  -- completed: accept only the exact three rendition URLs generated by the
  -- Hostinger video origin, all belonging to the same server-side media family.
  IF p_hd_url IS NULL
     OR p_sd_url IS NULL
     OR p_low_url IS NULL
     OR p_hd_url !~ E'^https://video\\.kletterwelt-sauerland\\.de/videos/[A-Za-z0-9_-]{1,128}/[A-Za-z0-9._-]+_hd\\.mp4$'
     OR p_sd_url !~ E'^https://video\\.kletterwelt-sauerland\\.de/videos/[A-Za-z0-9_-]{1,128}/[A-Za-z0-9._-]+_sd\\.mp4$'
     OR p_low_url !~ E'^https://video\\.kletterwelt-sauerland\\.de/videos/[A-Za-z0-9_-]{1,128}/[A-Za-z0-9._-]+_low\\.mp4$' THEN
    RAISE EXCEPTION 'Invalid completed video rendition URLs' USING ERRCODE = '22023';
  END IF;

  v_family := regexp_replace(p_hd_url, E'_hd\\.mp4$', '');
  IF regexp_replace(p_sd_url, E'_sd\\.mp4$', '') <> v_family
     OR regexp_replace(p_low_url, E'_low\\.mp4$', '') <> v_family THEN
    RAISE EXCEPTION 'Video renditions do not belong to one media family' USING ERRCODE = '22023';
  END IF;

  UPDATE public.boulders
  SET beta_video_status = 'ready',
      beta_video_job_id = p_job_id,
      beta_video_error = NULL,
      beta_video_url = p_hd_url,
      beta_video_urls = jsonb_build_object('hd', p_hd_url, 'sd', p_sd_url, 'low', p_low_url),
      beta_video_updated_at = now()
  WHERE id = p_boulder_id;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.sync_boulder_video_job(uuid, text, uuid, text, text, text, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_boulder_video_job(uuid, text, uuid, text, text, text, text, text)
  TO service_role;
