// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// NOTE: Native fetch is already overridden in main.tsx BEFORE this file is imported
// This ensures ALL Supabase requests are intercepted

// CRITICAL: Verify fetch override is active
console.log('[Supabase Client] 🔍 Checking fetch override:', {
  windowFetch: typeof window.fetch,
  fetchToString: window.fetch.toString().substring(0, 150),
  hasMainOverride: window.fetch.toString().includes('Main Fetch Override'),
});

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY
  });
}

// Create a completely safe storage adapter that NEVER throws errors
// This prevents any "Access to storage is not allowed" errors
const createSafeStorage = () => {
  return {
    getItem: (key: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return null;
        }
        // Check if storage is actually accessible
        const testKey = '__sb_storage_test__';
        try {
          localStorage.setItem(testKey, '1');
          localStorage.removeItem(testKey);
        } catch {
          // Storage is blocked, return null
          return null;
        }
        return localStorage.getItem(key);
      } catch (error) {
        // Silently return null - never throw
        return null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return;
        }
        // Check if storage is actually accessible
        const testKey = '__sb_storage_test__';
        try {
          localStorage.setItem(testKey, '1');
          localStorage.removeItem(testKey);
        } catch {
          // Storage is blocked, silently ignore
          return;
        }
        localStorage.setItem(key, value);
      } catch (error) {
        // Silently ignore - never throw
      }
    },
    removeItem: (key: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return;
        }
        // Check if storage is actually accessible
        const testKey = '__sb_storage_test__';
        try {
          localStorage.setItem(testKey, '1');
          localStorage.removeItem(testKey);
        } catch {
          // Storage is blocked, silently ignore
          return;
        }
        localStorage.removeItem(key);
      } catch (error) {
        // Silently ignore - never throw
      }
    },
  };
};

// Check if storage is available (but don't throw if it's not)
const isStorageAvailable = (() => {
  try {
    if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
      return false;
    }
    const testKey = '__sb_test__';
    localStorage.setItem(testKey, '1');
    localStorage.removeItem(testKey);
    return true;
  } catch (error) {
    return false;
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// CRITICAL: Use window.fetch directly - it's already overridden in index.html
// Don't create a custom fetch wrapper, just use window.fetch which is already intercepted
// This ensures the index.html override catches all requests
const customFetch = window.fetch;

// Wrap client creation in try-catch to prevent any initialization errors
let supabaseInstance: ReturnType<typeof createClient<Database>>;

// Log that we're creating the client
console.log('[Supabase Client] Creating client with custom fetch...');
console.log('[Supabase Client] Custom fetch function type:', typeof customFetch);
console.log('[Supabase Client] Custom fetch function:', customFetch.toString().substring(0, 100));

try {
  supabaseInstance = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: createSafeStorage(),
        persistSession: isStorageAvailable,
        autoRefreshToken: isStorageAvailable,
        detectSessionInUrl: false, // Disable URL session detection to avoid storage access
      },
      global: {
        fetch: customFetch as any, // Use custom fetch with logging - cast to any to ensure it's used
      },
    }
  );
  console.log('[Supabase Client] ✅ Client created successfully with custom fetch');
  
  // Test if custom fetch is actually being used by checking the client internals
  // @ts-ignore - accessing internal property for debugging
  if (supabaseInstance.rest && supabaseInstance.rest.fetch) {
    console.log('[Supabase Client] ✅ Custom fetch is set on client.rest.fetch');
  } else {
    console.warn('[Supabase Client] ⚠️ Custom fetch might not be set correctly');
  }
} catch (error) {
  // If client creation fails, create a minimal client without auth features
  console.warn('[Supabase] Error creating client, using fallback:', error);
  supabaseInstance = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: createSafeStorage(),
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
      global: {
        fetch: customFetch as any, // Use custom fetch with logging
      },
    }
  );
  console.log('[Supabase Client] ✅ Fallback client created with custom fetch');
}

export const supabase = supabaseInstance;