// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY
  });
}

// Create a completely safe storage adapter that NEVER throws errors
// This prevents any "Access to storage is not allowed" errors
const createSafeStorage = () => {
  return {
    getItem: (key: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return null;
        }
        return localStorage.getItem(key);
      } catch (error) {
        // Silently return null - never throw
        return null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return;
        }
        localStorage.setItem(key, value);
      } catch (error) {
        // Silently ignore - never throw
      }
    },
    removeItem: (key: string) => {
      try {
        if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
          return;
        }
        localStorage.removeItem(key);
      } catch (error) {
        // Silently ignore - never throw
      }
    },
  };
};

// Check if storage is available (but don't throw if it's not)
const isStorageAvailable = (() => {
  try {
    if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
      return false;
    }
    const testKey = '__sb_test__';
    localStorage.setItem(testKey, '1');
    localStorage.removeItem(testKey);
    return true;
  } catch (error) {
    return false;
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Wrap client creation in try-catch to prevent any initialization errors
let supabaseInstance: ReturnType<typeof createClient<Database>>;

try {
  supabaseInstance = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: createSafeStorage(),
        persistSession: isStorageAvailable,
        autoRefreshToken: isStorageAvailable,
        detectSessionInUrl: false, // Disable URL session detection to avoid storage access
      }
    }
  );
} catch (error) {
  // If client creation fails, create a minimal client without auth features
  console.warn('[Supabase] Error creating client, using fallback:', error);
  supabaseInstance = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: createSafeStorage(),
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      }
    }
  );
}

export const supabase = supabaseInstance;